# Generated by Django 2.2.6 on 2020-03-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='created',
        ),
    ]
