# Generated by Django 2.2.6 on 2020-03-03 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20200303_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Follow',
        ),
    ]
